// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account create"
                ],
                "responses": {}
            }
        },
        "/accounts/{ID}": {
            "get": {
                "description": "Get Account By ID data by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get Account By ID"
                ],
                "summary": "Get Account By Id",
                "responses": {}
            }
        },
        "/token/renew_access": {
            "post": {
                "responses": {}
            }
        },
        "/transfers": {
            "post": {
                "responses": {}
            }
        },
        "/users": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User create"
                ],
                "responses": {}
            }
        },
        "/users/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login User"
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Simple Bank Service API",
	Description:      "A Simple Bank service API in Go using Gin framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
