// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/movie.proto

package go_grpc_crud

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Movie struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genre                string   `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{0}
}

func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (m *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(m, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movie) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

type CreateMovieRequest struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieRequest) Reset()         { *m = CreateMovieRequest{} }
func (m *CreateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMovieRequest) ProtoMessage()    {}
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{1}
}

func (m *CreateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieRequest.Unmarshal(m, b)
}
func (m *CreateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieRequest.Marshal(b, m, deterministic)
}
func (m *CreateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieRequest.Merge(m, src)
}
func (m *CreateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMovieRequest.Size(m)
}
func (m *CreateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieRequest proto.InternalMessageInfo

func (m *CreateMovieRequest) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type CreateMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieResponse) Reset()         { *m = CreateMovieResponse{} }
func (m *CreateMovieResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMovieResponse) ProtoMessage()    {}
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{2}
}

func (m *CreateMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieResponse.Unmarshal(m, b)
}
func (m *CreateMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieResponse.Marshal(b, m, deterministic)
}
func (m *CreateMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieResponse.Merge(m, src)
}
func (m *CreateMovieResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMovieResponse.Size(m)
}
func (m *CreateMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieResponse proto.InternalMessageInfo

func (m *CreateMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type ReadMovieRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMovieRequest) Reset()         { *m = ReadMovieRequest{} }
func (m *ReadMovieRequest) String() string { return proto.CompactTextString(m) }
func (*ReadMovieRequest) ProtoMessage()    {}
func (*ReadMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{3}
}

func (m *ReadMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMovieRequest.Unmarshal(m, b)
}
func (m *ReadMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMovieRequest.Marshal(b, m, deterministic)
}
func (m *ReadMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMovieRequest.Merge(m, src)
}
func (m *ReadMovieRequest) XXX_Size() int {
	return xxx_messageInfo_ReadMovieRequest.Size(m)
}
func (m *ReadMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMovieRequest proto.InternalMessageInfo

func (m *ReadMovieRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMovieResponse) Reset()         { *m = ReadMovieResponse{} }
func (m *ReadMovieResponse) String() string { return proto.CompactTextString(m) }
func (*ReadMovieResponse) ProtoMessage()    {}
func (*ReadMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{4}
}

func (m *ReadMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMovieResponse.Unmarshal(m, b)
}
func (m *ReadMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMovieResponse.Marshal(b, m, deterministic)
}
func (m *ReadMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMovieResponse.Merge(m, src)
}
func (m *ReadMovieResponse) XXX_Size() int {
	return xxx_messageInfo_ReadMovieResponse.Size(m)
}
func (m *ReadMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMovieResponse proto.InternalMessageInfo

func (m *ReadMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type ReadMoviesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMoviesRequest) Reset()         { *m = ReadMoviesRequest{} }
func (m *ReadMoviesRequest) String() string { return proto.CompactTextString(m) }
func (*ReadMoviesRequest) ProtoMessage()    {}
func (*ReadMoviesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{5}
}

func (m *ReadMoviesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMoviesRequest.Unmarshal(m, b)
}
func (m *ReadMoviesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMoviesRequest.Marshal(b, m, deterministic)
}
func (m *ReadMoviesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMoviesRequest.Merge(m, src)
}
func (m *ReadMoviesRequest) XXX_Size() int {
	return xxx_messageInfo_ReadMoviesRequest.Size(m)
}
func (m *ReadMoviesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMoviesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMoviesRequest proto.InternalMessageInfo

type ReadMoviesResponse struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMoviesResponse) Reset()         { *m = ReadMoviesResponse{} }
func (m *ReadMoviesResponse) String() string { return proto.CompactTextString(m) }
func (*ReadMoviesResponse) ProtoMessage()    {}
func (*ReadMoviesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{6}
}

func (m *ReadMoviesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMoviesResponse.Unmarshal(m, b)
}
func (m *ReadMoviesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMoviesResponse.Marshal(b, m, deterministic)
}
func (m *ReadMoviesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMoviesResponse.Merge(m, src)
}
func (m *ReadMoviesResponse) XXX_Size() int {
	return xxx_messageInfo_ReadMoviesResponse.Size(m)
}
func (m *ReadMoviesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMoviesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMoviesResponse proto.InternalMessageInfo

func (m *ReadMoviesResponse) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type UpdateMovieRequest struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMovieRequest) Reset()         { *m = UpdateMovieRequest{} }
func (m *UpdateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMovieRequest) ProtoMessage()    {}
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{7}
}

func (m *UpdateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMovieRequest.Unmarshal(m, b)
}
func (m *UpdateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMovieRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMovieRequest.Merge(m, src)
}
func (m *UpdateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMovieRequest.Size(m)
}
func (m *UpdateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMovieRequest proto.InternalMessageInfo

func (m *UpdateMovieRequest) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type UpdateMovieResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMovieResponse) Reset()         { *m = UpdateMovieResponse{} }
func (m *UpdateMovieResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMovieResponse) ProtoMessage()    {}
func (*UpdateMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{8}
}

func (m *UpdateMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMovieResponse.Unmarshal(m, b)
}
func (m *UpdateMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMovieResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMovieResponse.Merge(m, src)
}
func (m *UpdateMovieResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMovieResponse.Size(m)
}
func (m *UpdateMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMovieResponse proto.InternalMessageInfo

func (m *UpdateMovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

type DeleteMovieRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{9}
}

func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(m, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteMovieResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieResponse) Reset()         { *m = DeleteMovieResponse{} }
func (m *DeleteMovieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieResponse) ProtoMessage()    {}
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{10}
}

func (m *DeleteMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieResponse.Unmarshal(m, b)
}
func (m *DeleteMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieResponse.Merge(m, src)
}
func (m *DeleteMovieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieResponse.Size(m)
}
func (m *DeleteMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieResponse proto.InternalMessageInfo

func (m *DeleteMovieResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Movie)(nil), "proto.Movie")
	proto.RegisterType((*CreateMovieRequest)(nil), "proto.CreateMovieRequest")
	proto.RegisterType((*CreateMovieResponse)(nil), "proto.CreateMovieResponse")
	proto.RegisterType((*ReadMovieRequest)(nil), "proto.ReadMovieRequest")
	proto.RegisterType((*ReadMovieResponse)(nil), "proto.ReadMovieResponse")
	proto.RegisterType((*ReadMoviesRequest)(nil), "proto.ReadMoviesRequest")
	proto.RegisterType((*ReadMoviesResponse)(nil), "proto.ReadMoviesResponse")
	proto.RegisterType((*UpdateMovieRequest)(nil), "proto.UpdateMovieRequest")
	proto.RegisterType((*UpdateMovieResponse)(nil), "proto.UpdateMovieResponse")
	proto.RegisterType((*DeleteMovieRequest)(nil), "proto.DeleteMovieRequest")
	proto.RegisterType((*DeleteMovieResponse)(nil), "proto.DeleteMovieResponse")
}

func init() { proto.RegisterFile("proto/movie.proto", fileDescriptor_78364ce9948b3a40) }

var fileDescriptor_78364ce9948b3a40 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3f, 0x6f, 0xf2, 0x30,
	0x10, 0xc6, 0x21, 0x28, 0xbc, 0x70, 0xa0, 0x57, 0xc5, 0x54, 0xaa, 0xc9, 0x84, 0x2c, 0x86, 0x2e,
	0x80, 0x44, 0x87, 0xfe, 0x59, 0x2a, 0x41, 0x45, 0xa7, 0x2e, 0xa9, 0xba, 0x74, 0xa3, 0xc9, 0x09,
	0x45, 0x02, 0x92, 0xc6, 0x06, 0xf5, 0x3b, 0xf7, 0x4b, 0x54, 0xd8, 0xc6, 0x72, 0xe2, 0x0c, 0xa5,
	0x53, 0x72, 0x77, 0xcf, 0xfd, 0x2e, 0x77, 0x4f, 0xa0, 0x97, 0xe5, 0xa9, 0x48, 0xa7, 0xdb, 0xf4,
	0x90, 0xe0, 0x44, 0xbe, 0x13, 0x5f, 0x3e, 0xd8, 0x02, 0xfc, 0x97, 0x63, 0x96, 0xfc, 0x07, 0x2f,
	0x89, 0x69, 0x7d, 0x58, 0xbf, 0x6e, 0x87, 0x5e, 0x12, 0x93, 0x4b, 0xf0, 0x45, 0x22, 0x36, 0x48,
	0x3d, 0x99, 0x52, 0xc1, 0x31, 0xbb, 0xc6, 0x5d, 0x8e, 0xb4, 0xa1, 0xb2, 0x32, 0x60, 0x77, 0x40,
	0x16, 0x39, 0xae, 0x04, 0x4a, 0x54, 0x88, 0x9f, 0x7b, 0xe4, 0x82, 0x30, 0xf0, 0xe5, 0x40, 0x09,
	0xed, 0xcc, 0xba, 0x6a, 0xf0, 0x44, 0x69, 0x54, 0x89, 0xdd, 0x43, 0xbf, 0xd0, 0xc9, 0xb3, 0x74,
	0xc7, 0xf1, 0x57, 0xad, 0x0c, 0x2e, 0x42, 0x5c, 0xc5, 0x85, 0x91, 0xa5, 0x25, 0xd8, 0x2d, 0xf4,
	0x2c, 0xcd, 0x19, 0xf0, 0xbe, 0xd5, 0xc8, 0x35, 0x9d, 0x3d, 0x00, 0xb1, 0x93, 0x1a, 0x37, 0x82,
	0xa6, 0xec, 0xe1, 0xb4, 0x3e, 0x6c, 0x38, 0x3c, 0x5d, 0x3b, 0x9e, 0xe8, 0x2d, 0x8b, 0xff, 0x78,
	0xa2, 0x42, 0xe7, 0x19, 0x5b, 0x8c, 0x80, 0x3c, 0xe1, 0x06, 0x4b, 0x43, 0xcb, 0x47, 0x9a, 0x42,
	0xbf, 0xa0, 0xd2, 0x03, 0x28, 0xfc, 0xe3, 0xfb, 0x28, 0x42, 0xce, 0xa5, 0xb6, 0x15, 0x9e, 0xc2,
	0xd9, 0xb7, 0x07, 0x5d, 0xa9, 0x7d, 0xc5, 0xfc, 0x90, 0x44, 0x48, 0x96, 0xd0, 0xb1, 0x5c, 0x24,
	0x03, 0xfd, 0x2d, 0xee, 0x3f, 0x11, 0x04, 0x55, 0x25, 0x35, 0x90, 0xd5, 0xc8, 0x23, 0xb4, 0x9e,
	0x51, 0x28, 0xc8, 0x95, 0x56, 0x96, 0x3d, 0x0e, 0xa8, 0x5b, 0x30, 0x80, 0x39, 0xb4, 0x4f, 0x00,
	0x4e, 0x1c, 0xe1, 0xc9, 0xc8, 0x60, 0x50, 0x51, 0x31, 0x8c, 0x25, 0x74, 0xac, 0x7b, 0x9b, 0x65,
	0x5c, 0xf7, 0xcc, 0x32, 0x15, 0xf6, 0x28, 0x8e, 0x75, 0x56, 0xc3, 0x71, 0x0d, 0x31, 0x9c, 0x0a,
	0x17, 0x58, 0x6d, 0x1e, 0xbc, 0x53, 0xfc, 0x5a, 0x6d, 0xb3, 0x0d, 0x4e, 0xa2, 0x74, 0x3b, 0x5d,
	0xa7, 0xe3, 0x75, 0x9e, 0x45, 0xe3, 0x28, 0xdf, 0xc7, 0x1f, 0x4d, 0xd9, 0x78, 0xf3, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x87, 0x86, 0xbf, 0xdb, 0xe0, 0x03, 0x00, 0x00,
}
